apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-depl
  namespace: talenthub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user-service:dev # 🔁 LOCAL image tag for development
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: DATABASE_URL
          envFrom:
            - configMapRef:
                name: common-config

---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
  namespace: talenthub
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3001
      targetPort: 3001